# THE FOLLOWING ACTIONS CODE IS FROM THE PSYCH ENGINE REPO: https://github.com/ShadowMario/FNF-PsychEngine/blob/main/.github/workflows/main.yml

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ReleaseBuild:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install lime 8.0.0
          haxelib install openfl
          haxelib install flixel 4.11.0       
          haxelib remove flixel-addons
          haxelib remove flixel-tools
          haxelib remove flixel-ui
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 2.9.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hxCodec 2.5.1          
          haxelib install linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib install hxcpp-debug-server
          haxelib list
        shell: cmd
      - name: Compile
        run: haxelib run lime build windows -release
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: ReleaseBuild
          path: export/release/windows/bin
